#line 1 "scanner.c"

#line 3 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[345] =
    {   0,
        0,    0,    0,    0,  136,  134,  133,  133,  107,  134,
       92,  108,  134,  125,  126,   90,   88,  117,   89,  114,
       91,   77,   77,  115,  116,  101,   93,  103,  121,    1,
       76,  129,  130,  110,   61,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  127,  109,  128,   13,   11,   12,
       13,    4,    5,    7,    8,   13,    6,    2,  133,  100,
        0,   84,    0,   98,  105,    0,   85,    0,   96,   94,
       95,  118,  123,    0,  131,   97,    0,   77,   77,    0,
        0,  113,  111,  102,   99,  119,  104,  112,  122,   76,

       76,   45,   76,   76,   76,   76,   21,   76,   76,   76,
       76,   76,    0,    0,   76,   76,   76,   18,   76,   76,
       24,   76,   46,   76,   76,   76,   76,   19,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   63,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  120,  106,   11,    0,   10,    0,
        0,    8,    3,    2,   84,    0,   85,    0,  124,    0,
        0,  131,   78,   81,   79,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   38,   76,   76,   76,    0,   82,
        0,    0,   83,    0,   76,   76,   76,   26,   76,   76,

       71,   33,   76,   20,   76,   57,   76,   76,   76,   49,
       44,   32,   76,   76,   48,   76,   22,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   65,   76,   76,   15,
       76,   76,    9,    0,    0,    0,    0,    0,    0,  132,
       76,   76,   76,   74,   76,   76,   76,   56,   25,   76,
       76,   76,   76,   76,   76,   47,   39,   76,   76,   28,
       76,   76,   59,   51,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   62,   76,   76,   42,   41,   76,   75,
       76,    0,    0,   76,   14,   16,   29,   66,   76,   76,
       76,   76,   43,   76,   72,   76,   76,   40,   76,   76,

       70,   76,   76,   76,   17,   76,   76,   76,   68,   76,
       76,   27,   86,   87,   76,   76,   69,   35,   76,   76,
       34,   31,   50,   36,   23,   76,   76,   73,   37,   64,
       76,   60,   76,   76,   55,   67,   52,   76,   58,   76,
       30,   54,   53,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   58,
       59,   30,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        1,    1,    1,    1,    4,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[357] =
    {   0,
        0,    0,   62,    0,  500,  501,  123,  126,  474,  125,
      473,  489,  123,  501,  501,  471,  470,  501,  108,  478,
      123,  123,  131,  471,  501,  112,  120,  128,  465,  501,
        0,  501,  501,  501,    0,  109,  109,  122,  447,  116,
      158,  127,  442,  133,  134,  142,  440,  141,  152,  161,
      170,  146,  438,  444,  501,  164,  501,  501,  484,  501,
      174,  501,  501,  501,  212,  463,  501,    0,  232,  501,
      179,  478,  480,  501,  501,  184,  473,  478,  501,  501,
      501,  501,  455,  467,    0,  501,  219,  225,  231,  160,
        0,  501,  501,  501,  501,  501,  501,  501,  501,    0,

      431,  418,  440,  425,  434,  419,    0,  423,  433,  417,
      421,  204,  192,  191,  421,  418,  416,    0,  413,  414,
        0,  412,  408,  410,  412,  405,  408,    0,  202,  418,
      402,  398,  407,  406,  405,  413,  413,  405,  394,  398,
      408,    0,  409,  392,  399,  389,  389,  392,  162,  388,
      385,  397,  392,  391,  501,  501,  432,  242,  501,  430,
      241,  247,  501,    0,  501,  248,  501,  194,  501,  420,
      252,    0,  252,  257,    0,  381,  381,  385,  381,  391,
      388,  371,  370,  383,    0,  382,  371,  380,  251,  501,
      416,  268,  501,  415,  364,  380,  379,    0,  366,  231,

        0,    0,  376,    0,  361,    0,  373,  355,  356,    0,
        0,    0,  349,  361,    0,  353,  350,  365,  348,  345,
      235,  347,  359,  349,  358,  357,    0,  356,  359,    0,
      355,  346,  266,  276,  386,  388,  279,  381,  386,  501,
      331,  349,  332,    0,  339,  341,  339,    0,    0,  331,
      329,  331,  339,  331,  323,    0,    0,  324,  336,    0,
      331,  326,    0,    0,  332,  331,  318,  332,  316,  318,
      317,  327,  326,    0,  306,  312,    0,    0,  320,    0,
      320,  353,  349,  322,    0,    0,    0,    0,  307,  301,
      300,  314,    0,  305,    0,  279,  274,    0,  269,  253,

        0,  257,  255,  260,    0,  261,  248,  258,    0,  244,
      258,    0,  501,  501,  256,  241,    0,    0,  242,  235,
        0,    0,    0,    0,    0,  235,  238,    0,    0,    0,
      237,    0,  248,  187,    0,    0,    0,  160,    0,  165,
        0,    0,    0,  501,  311,  315,  317,  321,  323,  327,
      331,  135,  335,  339,  343,  347
    } ;

static const flex_int16_t yy_def[357] =
    {   0,
      344,    1,  344,    3,  344,  344,  344,  344,  344,  345,
      344,  344,  346,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      347,  344,  344,  344,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  344,  344,  344,  344,  344,  344,
      348,  344,  344,  344,  344,  344,  344,  349,  344,  344,
      345,  344,  345,  344,  344,  346,  344,  346,  344,  344,
      344,  344,  344,  350,  351,  344,  344,  344,  344,  344,
      352,  344,  344,  344,  344,  344,  344,  344,  344,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  353,  354,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  344,  344,  344,  348,  344,  348,
      344,  344,  344,  349,  344,  355,  344,  356,  344,  350,
      350,  351,  344,  344,  352,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  353,  344,
      353,  354,  344,  354,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  344,  355,  344,  355,  356,  344,  356,  344,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  344,  344,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  344,  344,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,    0,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344
    } ;

static const flex_int16_t yy_nxt[564] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   31,
       32,    6,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   31,   31,   42,   43,   31,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   31,   31,   55,
       56,   57,   58,   59,   60,   58,   58,   61,   58,   58,
       58,   62,   63,   58,   58,   64,   58,   58,   58,   65,
       65,   65,   65,   66,   58,   58,   67,   58,   58,   58,
       68,   68,   58,   58,   58,   58,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   58,   58,   58,   69,   69,   69,   69,   69,   69,
       72,   77,   81,   82,   84,   93,   94,  175,   87,   85,
       88,   88,   88,   89,   95,   96,   87,   86,   89,   89,
       89,   89,   97,   98,   78,  101,   73,  106,  104,   90,
      105,  102,  110,  113,  111,  103,  114,  121,  125,  129,
      107,  108,  126,  112,  122,  123,  136,  174,  174,  159,
       91,  132,  127,  130,  165,  133,  128,  138,  131,  155,
      134,  139,  167,  115,  151,  137,  140,  190,  152,  193,

      141,  116,  238,  142,  117,  160,  118,  119,  343,  120,
       73,  143,  147,  148,  144,   78,  226,  145,  342,  146,
      227,  149,  194,  191,  156,  239,  341,  161,  150,  162,
      162,  162,  162,   69,   69,   69,  173,  173,  173,  173,
       87,  186,   88,   88,   88,   89,   87,  159,   89,   89,
       89,   89,  206,  235,  187,  207,  190,  188,  233,  233,
      233,  233,  161,  171,  162,  162,  162,  162,  240,  173,
      173,  173,  173,  160,  174,  174,  193,  257,  271,  236,
      258,  235,  191,  233,  233,  233,  233,  238,  340,  272,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  194,

      330,  329,  328,  327,  326,  325,  324,  236,  323,  322,
      239,   71,   71,   71,   71,   76,   76,   76,   76,  100,
      100,  158,  158,  158,  158,  164,  164,  170,  170,  170,
      170,  172,  321,  172,  172,  189,  189,  189,  189,  192,
      192,  192,  192,  234,  234,  234,  234,  237,  237,  237,
      237,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  344,  283,
      344,  282,  281,  280,  279,  278,  277,  276,  275,  274,

      273,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  256,  255,  254,  253,  344,  344,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  171,  344,  157,  232,  231,  230,  229,  228,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  171,  169,
      344,  168,  344,  166,  163,  157,  154,  153,  135,  124,
      109,   99,   92,   83,   80,   79,   75,   74,   70,  344,

        5,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344
    } ;

static const flex_int16_t yy_chk[564] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    7,    7,    7,    8,    8,    8,
       10,   13,   19,   19,   21,   26,   26,  352,   22,   21,
       22,   22,   22,   22,   27,   27,   23,   21,   23,   23,
       23,   23,   28,   28,   13,   36,   10,   38,   37,   22,
       37,   36,   40,   41,   40,   36,   41,   42,   44,   45,
       38,   38,   44,   40,   42,   42,   48,   90,   90,   61,
       22,   46,   44,   45,   71,   46,   44,   49,   45,   56,
       46,   49,   76,   41,   52,   48,   50,  113,   52,  114,

       50,   41,  168,   50,   41,   61,   41,   41,  340,   41,
       71,   50,   51,   51,   50,   76,  149,   50,  338,   50,
      149,   51,  114,  113,   56,  168,  334,   65,   51,   65,
       65,   65,   65,   69,   69,   69,   87,   87,   87,   87,
       88,  112,   88,   88,   88,   88,   89,  158,   89,   89,
       89,   89,  129,  166,  112,  129,  189,  112,  161,  161,
      161,  161,  162,  171,  162,  162,  162,  162,  171,  173,
      173,  173,  173,  158,  174,  174,  192,  200,  221,  166,
      200,  234,  189,  233,  233,  233,  233,  237,  333,  221,
      331,  327,  326,  320,  319,  316,  315,  311,  310,  192,

      308,  307,  306,  304,  303,  302,  300,  234,  299,  297,
      237,  345,  345,  345,  345,  346,  346,  346,  346,  347,
      347,  348,  348,  348,  348,  349,  349,  350,  350,  350,
      350,  351,  296,  351,  351,  353,  353,  353,  353,  354,
      354,  354,  354,  355,  355,  355,  355,  356,  356,  356,
      356,  294,  292,  291,  290,  289,  284,  283,  282,  281,
      279,  276,  275,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  262,  261,  259,  258,  255,  254,  253,  252,
      251,  250,  247,  246,  245,  243,  242,  241,  239,  238,
      236,  235,  232,  231,  229,  228,  226,  225,  224,  223,

      222,  220,  219,  218,  217,  216,  214,  213,  209,  208,
      207,  205,  203,  199,  197,  196,  195,  194,  191,  188,
      187,  186,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  170,  160,  157,  154,  153,  152,  151,  150,  148,
      147,  146,  145,  144,  143,  141,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  130,  127,  126,  125,
      124,  123,  122,  120,  119,  117,  116,  115,  111,  110,
      109,  108,  106,  105,  104,  103,  102,  101,   84,   83,
       78,   77,   73,   72,   66,   59,   54,   53,   47,   43,
       39,   29,   24,   20,   17,   16,   12,   11,    9,    5,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer/scanner.l"
#line 2 "src/lexer/scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "parser.h"

extern int yylineno;
extern char* yytext;

void yyerror(const char* msg);
#line 725 "scanner.c"
/* État exclusif pour les décorateurs @app::server(port=8080) */

#line 728 "scanner.c"

#define INITIAL 0
#define DECORATOR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "src/lexer/scanner.l"


#line 22 "src/lexer/scanner.l"
 /* ============================================ */
 /*   DÉCORATEURS  @name  ou  @ns::name(...)     */
 /* ============================================ */

#line 954 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 501 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "src/lexer/scanner.l"
{ BEGIN(DECORATOR); return TOKEN_AT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "src/lexer/scanner.l"
{
    yylval.string = strdup(yytext);
    return TOKEN_IDENTIFIER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "src/lexer/scanner.l"
{ return TOKEN_DOUBLE_COLON; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "src/lexer/scanner.l"
{ return TOKEN_LPAREN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "src/lexer/scanner.l"
{ BEGIN(INITIAL); return TOKEN_RPAREN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "src/lexer/scanner.l"
{ return TOKEN_ASSIGN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "src/lexer/scanner.l"
{ return TOKEN_COMMA; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "src/lexer/scanner.l"
{ yylval.number = atoi(yytext); return TOKEN_NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "src/lexer/scanner.l"
{ yylval.float_val = atof(yytext); return TOKEN_FLOAT; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 39 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* s = malloc(len - 1);
    int i, j = 0;
    for (i = 1; i < len - 1; i++) s[j++] = yytext[i];
    s[j] = '\0';
    yylval.string = s;
    return TOKEN_STRING;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "src/lexer/scanner.l"
{ /* ignorer les espaces */ }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 49 "src/lexer/scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "src/lexer/scanner.l"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK
/* ============================================ */
/*              MOTS-CLÉS                       */
/* ============================================ */
case 14:
YY_RULE_SETUP
#line 56 "src/lexer/scanner.l"
{ return TOKEN_ASYNC; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "src/lexer/scanner.l"
{ return TOKEN_USE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "src/lexer/scanner.l"
{ return TOKEN_AWAIT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "src/lexer/scanner.l"
{ return TOKEN_SPAWN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "src/lexer/scanner.l"
{ return TOKEN_FN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "src/lexer/scanner.l"
{ return TOKEN_LET; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "src/lexer/scanner.l"
{ return TOKEN_LET; }     /* alias backward-compat */
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "src/lexer/scanner.l"
{ return TOKEN_CONST; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "src/lexer/scanner.l"
{ return TOKEN_RETURN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "src/lexer/scanner.l"
{ return TOKEN_RETURN; }  /* alias backward-compat */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "src/lexer/scanner.l"
{ return TOKEN_IF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "src/lexer/scanner.l"
{ return TOKEN_ELSE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "src/lexer/scanner.l"
{ return TOKEN_FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "src/lexer/scanner.l"
{ return TOKEN_WHILE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "src/lexer/scanner.l"
{ return TOKEN_LOOP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "src/lexer/scanner.l"
{ return TOKEN_BREAK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "src/lexer/scanner.l"
{ return TOKEN_CONTINUE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "src/lexer/scanner.l"
{ return TOKEN_LAMBDA; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "src/lexer/scanner.l"
{ return TOKEN_NNL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "src/lexer/scanner.l"
{ return TOKEN_JMP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "src/lexer/scanner.l"
{ return TOKEN_IMPORT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "src/lexer/scanner.l"
{ return TOKEN_EXPORT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "src/lexer/scanner.l"
{ return TOKEN_PACKET; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "src/lexer/scanner.l"
{ return TOKEN_STRUCT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "src/lexer/scanner.l"
{ return TOKEN_ENUM; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "src/lexer/scanner.l"
{ return TOKEN_IMPL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "src/lexer/scanner.l"
{ return TOKEN_MATCH; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "src/lexer/scanner.l"
{ return TOKEN_TYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "src/lexer/scanner.l"
{ return TOKEN_TRUE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "src/lexer/scanner.l"
{ return TOKEN_FALSE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "src/lexer/scanner.l"
{ return TOKEN_NIL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "src/lexer/scanner.l"
{ return TOKEN_AS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "src/lexer/scanner.l"
{ return TOKEN_IN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "src/lexer/scanner.l"
{ return TOKEN_FROM; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "src/lexer/scanner.l"
{ return TOKEN_PUB; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "src/lexer/scanner.l"
{ return TOKEN_NEW; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "src/lexer/scanner.l"
{ return TOKEN_MODULE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "src/lexer/scanner.l"
{ return TOKEN_ONLY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "src/lexer/scanner.l"
{ return TOKEN_SANDBOX; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "src/lexer/scanner.l"
{ return TOKEN_ALLOW_FFI; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "src/lexer/scanner.l"
{ return TOKEN_SECURITY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "src/lexer/scanner.l"
{ return TOKEN_EXTENDS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "src/lexer/scanner.l"
{ return TOKEN_DICT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "src/lexer/scanner.l"
{ return TOKEN_MAP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "src/lexer/scanner.l"
{ return TOKEN_TIMEOUT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "src/lexer/scanner.l"
{ return TOKEN_MUTS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "src/lexer/scanner.l"
{ return TOKEN_UNSAFE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "src/lexer/scanner.l"
{ return TOKEN_UNDERSCORE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "src/lexer/scanner.l"
{ return TOKEN_SYSF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "src/lexer/scanner.l"
{ return TOKEN_SH; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "src/lexer/scanner.l"
{ return TOKEN_SWITCH; }
	YY_BREAK
/* Try/Catch/Throw */
case 65:
YY_RULE_SETUP
#line 108 "src/lexer/scanner.l"
{ return TOKEN_TRY; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "src/lexer/scanner.l"
{ return TOKEN_CATCH; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "src/lexer/scanner.l"
{ return TOKEN_FINALLY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "src/lexer/scanner.l"
{ return TOKEN_THROW; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "src/lexer/scanner.l"
{ return TOKEN_EXCEPT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "src/lexer/scanner.l"
{ return TOKEN_RAISE; }
	YY_BREAK
/* Types primitifs (traités comme identifiants) */
case 71:
YY_RULE_SETUP
#line 116 "src/lexer/scanner.l"
{ yylval.string = strdup(yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "src/lexer/scanner.l"
{ yylval.string = strdup(yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "src/lexer/scanner.l"
{ yylval.string = strdup(yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "src/lexer/scanner.l"
{ yylval.string = strdup(yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "src/lexer/scanner.l"
{ yylval.string = strdup(yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
/* ============================================ */
/*              IDENTIFIANTS                    */
/* ============================================ */
case 76:
YY_RULE_SETUP
#line 126 "src/lexer/scanner.l"
{ 
    yylval.string = strdup(yytext); 
    return TOKEN_IDENTIFIER; 
}
	YY_BREAK
/* ============================================ */
/*              NOMBRES                         */
/* ============================================ */
case 77:
YY_RULE_SETUP
#line 135 "src/lexer/scanner.l"
{
    yylval.number = atoi(yytext);
    return TOKEN_NUMBER;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 140 "src/lexer/scanner.l"
{
    yylval.float_val = atof(yytext);
    return TOKEN_FLOAT;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 145 "src/lexer/scanner.l"
{
    yylval.number = strtol(yytext, NULL, 16);
    return TOKEN_NUMBER;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "src/lexer/scanner.l"
{
    yylval.number = strtol(yytext, NULL, 8);
    return TOKEN_NUMBER;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "src/lexer/scanner.l"
{
    yylval.number = strtol(yytext + 2, NULL, 2);
    return TOKEN_NUMBER;
}
	YY_BREAK
/* ============================================ */
/*              F-STRINGS                       */
/* ============================================ */
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 164 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* raw = malloc(len - 2);
    int i, j = 0;
    for (i = 2; i < len - 1; i++) {
        if (yytext[i] == '\\' && i+1 < len-1) {
            i++;
            switch (yytext[i]) {
                case 'n': raw[j++] = '\n'; break;
                case 't': raw[j++] = '\t'; break;
                case 'r': raw[j++] = '\r'; break;
                case '\\': raw[j++] = '\\'; break;
                case '"': raw[j++] = '"'; break;
                case '\'': raw[j++] = '\''; break;
                case '{': raw[j++] = '{'; break;
                case '}': raw[j++] = '}'; break;
                /* Support ANSI Escape \033 ou \x1b */
                case '0':
                    if (i+2 < len-1 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        raw[j++] = '\033';
                        i += 2;
                    } else {
                        raw[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-1 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        raw[j++] = '\033';
                        i += 2;
                    } else {
                        raw[j++] = 'x';
                    }
                    break;
                default: raw[j++] = yytext[i]; break;
            }
        } else {
            raw[j++] = yytext[i];
        }
    }
    raw[j] = '\0';
    yylval.string = raw;
    return TOKEN_F_STRING;
}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 208 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* raw = malloc(len - 2);
    int i, j = 0;
    for (i = 2; i < len - 1; i++) {
        if (yytext[i] == '\\' && i+1 < len-1) {
            i++;
            switch (yytext[i]) {
                case 'n': raw[j++] = '\n'; break;
                case 't': raw[j++] = '\t'; break;
                case 'r': raw[j++] = '\r'; break;
                case '\\': raw[j++] = '\\'; break;
                case '\'': raw[j++] = '\''; break;
                case '"': raw[j++] = '"'; break;
                case '{': raw[j++] = '{'; break;
                case '}': raw[j++] = '}'; break;
                /* Support ANSI Escape */
                case '0':
                    if (i+2 < len-1 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        raw[j++] = '\033';
                        i += 2;
                    } else {
                        raw[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-1 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        raw[j++] = '\033';
                        i += 2;
                    } else {
                        raw[j++] = 'x';
                    }
                    break;
                default: raw[j++] = yytext[i]; break;
            }
        } else {
            raw[j++] = yytext[i];
        }
    }
    raw[j] = '\0';
    yylval.string = raw;
    return TOKEN_F_STRING;
}
	YY_BREAK
/* ============================================ */
/*              CHAÎNES                        */
/* ============================================ */
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 256 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* str = malloc(len - 1);
    int i, j = 0;
    for (i = 1; i < len - 1; i++) {
        if (yytext[i] == '\\' && i+1 < len-1) {
            i++;
            switch (yytext[i]) {
                case 'n': str[j++] = '\n'; break;
                case 't': str[j++] = '\t'; break;
                case 'r': str[j++] = '\r'; break;
                case '\\': str[j++] = '\\'; break;
                case '"': str[j++] = '"'; break;
                case '\'': str[j++] = '\''; break;
                /* Support ANSI Escape */
                case '0':
                    if (i+2 < len-1 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-1 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = 'x';
                    }
                    break;
                default: str[j++] = yytext[i]; break;
            }
        } else {
            str[j++] = yytext[i];
        }
    }
    str[j] = '\0';
    yylval.string = str;
    return TOKEN_STRING;
}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 298 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* str = malloc(len - 1);
    int i, j = 0;
    for (i = 1; i < len - 1; i++) {
        if (yytext[i] == '\\' && i+1 < len-1) {
            i++;
            switch (yytext[i]) {
                case 'n': str[j++] = '\n'; break;
                case 't': str[j++] = '\t'; break;
                case 'r': str[j++] = '\r'; break;
                case '\\': str[j++] = '\\'; break;
                case '\'': str[j++] = '\''; break;
                case '"': str[j++] = '"'; break;
                /* Support ANSI Escape */
                case '0':
                    if (i+2 < len-1 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-1 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = 'x';
                    }
                    break;
                default: str[j++] = yytext[i]; break;
            }
        } else {
            str[j++] = yytext[i];
        }
    }
    str[j] = '\0';
    yylval.string = str;
    return TOKEN_STRING;
}
	YY_BREAK
/* Chaînes multi-lignes */
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 341 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* str = malloc(len - 5);
    int i, j = 0;
    for (i = 3; i < len - 3; i++) {
        if (yytext[i] == '\\' && i+1 < len-3) {
            i++;
            switch (yytext[i]) {
                case 'n': str[j++] = '\n'; break;
                case 't': str[j++] = '\t'; break;
                case 'r': str[j++] = '\r'; break;
                case '\\': str[j++] = '\\'; break;
                case '"': str[j++] = '"'; break;
                /* Support ANSI Escape */
                case '0':
                    if (i+2 < len-3 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-3 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = 'x';
                    }
                    break;
                default: str[j++] = yytext[i]; break;
            }
        } else {
            str[j++] = yytext[i];
        }
    }
    str[j] = '\0';
    yylval.string = str;
    return TOKEN_STRING;
}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 382 "src/lexer/scanner.l"
{
    int len = strlen(yytext);
    char* str = malloc(len - 5);
    int i, j = 0;
    for (i = 3; i < len - 3; i++) {
        if (yytext[i] == '\\' && i+1 < len-3) {
            i++;
            switch (yytext[i]) {
                case 'n': str[j++] = '\n'; break;
                case 't': str[j++] = '\t'; break;
                case 'r': str[j++] = '\r'; break;
                case '\\': str[j++] = '\\'; break;
                case '\'': str[j++] = '\''; break;
                /* Support ANSI Escape */
                case '0':
                    if (i+2 < len-3 && yytext[i+1] == '3' && yytext[i+2] == '3') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = '0';
                    }
                    break;
                case 'x':
                    if (i+2 < len-3 && yytext[i+1] == '1' && yytext[i+2] == 'b') {
                        str[j++] = '\033';
                        i += 2;
                    } else {
                        str[j++] = 'x';
                    }
                    break;
                default: str[j++] = yytext[i]; break;
            }
        } else {
            str[j++] = yytext[i];
        }
    }
    str[j] = '\0';
    yylval.string = str;
    return TOKEN_STRING;
}
	YY_BREAK
/* ============================================ */
/*              OPÉRATEURS                      */
/* ============================================ */
case 88:
YY_RULE_SETUP
#line 427 "src/lexer/scanner.l"
{ return TOKEN_PLUS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 428 "src/lexer/scanner.l"
{ return TOKEN_MINUS; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 429 "src/lexer/scanner.l"
{ return TOKEN_MULTIPLY; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 430 "src/lexer/scanner.l"
{ return TOKEN_DIVIDE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 431 "src/lexer/scanner.l"
{ return TOKEN_MODULO; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 432 "src/lexer/scanner.l"
{ return TOKEN_ASSIGN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 433 "src/lexer/scanner.l"
{ return TOKEN_PLUS_ASSIGN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 434 "src/lexer/scanner.l"
{ return TOKEN_MINUS_ASSIGN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 435 "src/lexer/scanner.l"
{ return TOKEN_MULTIPLY_ASSIGN; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 436 "src/lexer/scanner.l"
{ return TOKEN_DIVIDE_ASSIGN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 437 "src/lexer/scanner.l"
{ return TOKEN_MODULO_ASSIGN; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 438 "src/lexer/scanner.l"
{ return TOKEN_EQ; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 439 "src/lexer/scanner.l"
{ return TOKEN_NEQ; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 440 "src/lexer/scanner.l"
{ return TOKEN_LT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 441 "src/lexer/scanner.l"
{ return TOKEN_LTE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 442 "src/lexer/scanner.l"
{ return TOKEN_GT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 443 "src/lexer/scanner.l"
{ return TOKEN_GTE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 444 "src/lexer/scanner.l"
{ return TOKEN_AND; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 445 "src/lexer/scanner.l"
{ return TOKEN_OR; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 446 "src/lexer/scanner.l"
{ return TOKEN_NOT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 447 "src/lexer/scanner.l"
{ return TOKEN_AMP; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 448 "src/lexer/scanner.l"
{ return TOKEN_PIPE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 449 "src/lexer/scanner.l"
{ return TOKEN_XOR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 450 "src/lexer/scanner.l"
{ return TOKEN_LSHIFT; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 451 "src/lexer/scanner.l"
{ return TOKEN_RSHIFT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 452 "src/lexer/scanner.l"
{ return TOKEN_DOUBLE_COLON; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 453 "src/lexer/scanner.l"
{ return TOKEN_DOT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 454 "src/lexer/scanner.l"
{ return TOKEN_COLON; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 455 "src/lexer/scanner.l"
{ return TOKEN_SEMICOLON; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 456 "src/lexer/scanner.l"
{ return TOKEN_COMMA; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 457 "src/lexer/scanner.l"
{ return TOKEN_ARROW; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 458 "src/lexer/scanner.l"
{ return TOKEN_FAT_ARROW; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 459 "src/lexer/scanner.l"
{ return TOKEN_PIPE_FORWARD; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 460 "src/lexer/scanner.l"
{ return TOKEN_OPTIONAL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 461 "src/lexer/scanner.l"
{ return TOKEN_COALESCE; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 462 "src/lexer/scanner.l"
{ return TOKEN_RANGE; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 463 "src/lexer/scanner.l"
{ return TOKEN_RANGE_INC; }
	YY_BREAK
/* ============================================ */
/*              DÉLIMITEURS                     */
/* ============================================ */
case 125:
YY_RULE_SETUP
#line 469 "src/lexer/scanner.l"
{ return TOKEN_LPAREN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 470 "src/lexer/scanner.l"
{ return TOKEN_RPAREN; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 471 "src/lexer/scanner.l"
{ return TOKEN_LBRACE; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 472 "src/lexer/scanner.l"
{ return TOKEN_RBRACE; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 473 "src/lexer/scanner.l"
{ return TOKEN_LBRACKET; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 474 "src/lexer/scanner.l"
{ return TOKEN_RBRACKET; }
	YY_BREAK
/* ============================================ */
/*              COMMENTAIRES                    */
/* ============================================ */
case 131:
YY_RULE_SETUP
#line 480 "src/lexer/scanner.l"
{ /* Ignorer */ }
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 481 "src/lexer/scanner.l"
{ /* Ignorer */ }
	YY_BREAK
/* ============================================ */
/*              ESPACES                         */
/* ============================================ */
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 487 "src/lexer/scanner.l"
{ /* Ignorer */ }
	YY_BREAK
/* ============================================ */
/*              CARACTÈRE INVALIDE              */
/* ============================================ */
case 134:
YY_RULE_SETUP
#line 493 "src/lexer/scanner.l"
{ 
    fprintf(stderr, "Error at line %d: Invalid character '%c' (ASCII %d)\n", 
            yylineno, yytext[0], yytext[0]);
    yyerror("Invalid character"); 
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 499 "src/lexer/scanner.l"
ECHO;
	YY_BREAK
#line 2014 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DECORATOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 344);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 499 "src/lexer/scanner.l"


/* ============================================ */
/*              FONCTIONS                       */
/* ============================================ */

void cleanup_scanner(void) {
    /* Rien à faire pour l'instant */
}

