#ifndef GOSCRIPT_TOKEN_H
#define GOSCRIPT_TOKEN_H

typedef enum {
    // Mots-clés
    TOKEN_FN, TOKEN_CLASS, TOKEN_ENUM, TOKEN_LET, TOKEN_CONST,
    TOKEN_USE, TOKEN_EXPORT, TOKEN_IF, TOKEN_ELSE, TOKEN_ASYNC, TOKEN_AWAIT,
    TOKEN_WHILE, TOKEN_FOR, TOKEN_RETURN,
    TOKEN_TRUE, TOKEN_FALSE,  // <-- AJOUTER CES LIGNES
    TOKEN_NIL, TOKEN_RETURN,                // Optionnel
    
    // Identifiants et valeurs
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,
    
    // Opérateurs et ponctuation
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL, TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_DOT, TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_COLON,
    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE,
    TOKEN_LBRACKET, TOKEN_RBRACKET,
    
    // Système spécifique
    TOKEN_GETLF, TOKEN_PRINT, TOKEN_INPUT,
    
    TOKEN_EOF, TOKEN_ERROR
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

#endif
